### ISSUE TITLE
I don't know what to put

### ISSUE THREAD

**Issue by idontknowbrh** [olybri/rllib#1]
Well, I'm a bit of an idiot and I don't know how to configure the cmake, could you help me with details?

**Comment by loriswit** [comment]
Can you elaborate on the part you're having trouble with?

Here are the commands that I would run in order to build the library:
```
git clone https://github.com/loriswit/rllib
cd rllib
mkdir build
cd build
cmake -G "Unix Makefiles" ..
cmake --build . --target rl
```
Of course, this requires CMake, Conan and a C++ compilator to be installed correctly. I choose to generate Unix Makefiles, but you may need a different generator depending on your build toolchain.

Note that I don't really maintain this library anymore (mostly because [this](https://github.com/byvar/ubi-canvas) exists), so use it with care.
